name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover -s . -p 'test_*.py'

  merge-to-staging:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development

      - name: Set up Git Config
        run: |
          git config --global user.email "karim3alaoui@gmail.com"
          git config --global user.name "karim-alaoui"

      - name: Checkout Staging Branch
        run: |
          git fetch
          git checkout staging

      - name: Merge Development into Staging
        run: |
          git merge origin/development --allow-unrelated-histories
          git push origin staging
        shell: /usr/bin/bash -e {0}