name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover -s . -p 'test_*.py'

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Staging
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: "ec2-13-210-247-21.ap-southeast-2.compute.amazonaws.com"
          REMOTE_USER: "ec2-user"
          SOURCE: "."
          TARGET: "/var/www/html"
          EXCLUDE: "/app.wsgi" # Exclude app.wsgi file from being deployed

