name : deploying to prod env

on:
  push:
    branches: 
      - production

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Production
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: "ec2-13-55-16-230.ap-southeast-2.compute.amazonaws.com"
          REMOTE_USER: "ec2-user"
          SOURCE: "."
          TARGET: "/var/www/html"
          EXCLUDE: "/app.wsgi,.git/*,.github/*"

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
    
      - name: Restart Apache
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@ec2-13-55-16-230.ap-southeast-2.compute.amazonaws.com "sudo systemctl restart httpd.service"